// SPDX-License-Identifier: MIT
/**
 * The candidate documents this repository seeds, and the CIDs that name them.
 *
 * `metadata/*.json` are the documents; `metadata/manifest.json` is the record of
 * the CID each one was pinned under. Both live in the repository so that the
 * bytes a CID names can be re-read and re-hashed at any time, offline. That is
 * the whole point: `bafyseededcandidate0` was believable only because nothing in
 * the repository could contradict it.
 *
 * The manifest is generated by `scripts/pin-metadata.ts` and checked by
 * `test/metadata.ts`, which recomputes every CID from the bytes beside it. A
 * hand-edited document therefore cannot silently keep an old CID — the test
 * fails, and so does `seedableCids()`, which verifies before it returns.
 *
 * It carries no timestamp or gateway URL: ADR-0010 keeps volatile fields out of
 * artifacts a check compares, because a re-pin that changed only the time would
 * show up as a diff and train the reader to ignore it.
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { computedCids, cidProblem, sameBlock } from "./cid";

export const METADATA_DIR = path.resolve(import.meta.dirname, "..", "metadata");
export const MANIFEST_NAME = "manifest.json";

/** The fields `web/src/lib/ipfs.ts` will render; anything else is dropped there. */
export interface CandidateMetadata {
  name: string;
  slogan?: string;
  description?: string;
}

/** One document and the CID it was pinned under. */
export interface ManifestEntry {
  /** File name inside `metadata/`, e.g. `candidate-1.json`. */
  file: string;
  /** The CID of exactly those bytes, as returned by the pinning service. */
  cid: string;
}

export interface Manifest {
  candidates: ManifestEntry[];
}

/** A document that is ready to be seeded. */
export interface CandidateDocument extends ManifestEntry {
  bytes: Uint8Array;
  metadata: CandidateMetadata;
}

const DOCUMENT_NAME = /^[a-z0-9][a-z0-9._-]*\.json$/;

/** Document file names in seed order — `manifest.json` is not a document. */
export async function documentFiles(directory: string = METADATA_DIR): Promise<string[]> {
  const entries = await readdir(directory);

  return entries.filter((name) => name.endsWith(".json") && name !== MANIFEST_NAME).sort();
}

/**
 * Why a parsed document cannot be rendered, or `null` when it can.
 *
 * Checked here rather than left to the card, because a document without a `name`
 * is seeded just as successfully as any other and would then render as
 * "候选人 #N" forever — a metadata file that silently does nothing.
 */
export function metadataProblem(value: unknown): string | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return "it is not a JSON object";
  }

  const document = value as Record<string, unknown>;
  if (typeof document.name !== "string" || document.name.length === 0) {
    return `"name" must be a non-empty string`;
  }

  for (const field of ["slogan", "description"] as const) {
    const value = document[field];
    if (value !== undefined && typeof value !== "string") {
      return `"${field}" is present but is not a string`;
    }
  }

  return null;
}

/** Reads the pinned manifest, or explains how to produce one. */
export async function readManifest(directory: string = METADATA_DIR): Promise<Manifest> {
  const file = path.join(directory, MANIFEST_NAME);

  let raw: string;
  try {
    raw = await readFile(file, "utf8");
  } catch {
    throw new Error(
      `no ${MANIFEST_NAME} beside the candidate documents (looked in ${directory}).\n` +
        `The manifest records the CID each document was pinned under, so seeding without one ` +
        `would mean guessing a CID — which is how the ballots ended up naming a string that is ` +
        `not a CID. Run: pnpm --filter @voting/contracts pin:metadata`,
    );
  }

  const parsed = JSON.parse(raw) as Manifest;
  if (!Array.isArray(parsed.candidates) || parsed.candidates.length === 0) {
    throw new Error(`${MANIFEST_NAME} has no "candidates" array; nothing to seed.`);
  }

  return parsed;
}

/**
 * Everything wrong with the manifest and the documents it names.
 *
 * Returns a list rather than throwing on the first problem, because these are
 * read together at seed time and a report that names one file per run turns a
 * single mistake into several round trips.
 */
export async function manifestProblems(directory: string = METADATA_DIR): Promise<string[]> {
  const problems: string[] = [];

  const manifest = await readManifest(directory);
  const files = await documentFiles(directory);
  const named = manifest.candidates.map((entry) => entry.file);

  for (const file of files) {
    if (!DOCUMENT_NAME.test(file)) {
      problems.push(`${file}: a document file name must be lower case, URL-safe and end in .json`);
    }
    if (!named.includes(file)) {
      problems.push(
        `${file}: is not in ${MANIFEST_NAME}, so it is not pinned and cannot be seeded`,
      );
    }
  }

  const seen = new Set<string>();
  for (const entry of manifest.candidates) {
    if (seen.has(entry.file)) {
      problems.push(
        `${entry.file}: appears twice in ${MANIFEST_NAME}, so its candidate id is ambiguous`,
      );
    }
    seen.add(entry.file);

    const shape = cidProblem(entry.cid);
    if (shape !== null) {
      problems.push(`${entry.file}: the manifest CID ${shape}`);
      continue;
    }

    let bytes: Uint8Array;
    try {
      bytes = new Uint8Array(await readFile(path.join(directory, entry.file)));
    } catch {
      problems.push(`${entry.file}: is named in ${MANIFEST_NAME} but not in the directory`);
      continue;
    }

    const expected = computedCids(bytes);
    if (!sameBlock(entry.cid, expected.dagPb) && !sameBlock(entry.cid, expected.raw)) {
      problems.push(
        `${entry.file}: the manifest CID does not name these bytes. ` +
          `Recorded ${entry.cid}; the file is ${expected.dagPb} (dag-pb, CIDv1) or ` +
          `${expected.raw} (raw). Re-pin it, or revert the edit.`,
      );
      continue;
    }

    const metadata = metadataProblem(JSON.parse(new TextDecoder().decode(bytes)));
    if (metadata !== null) {
      problems.push(`${entry.file}: ${metadata}`);
    }
  }

  return problems;
}

/**
 * The CIDs to seed, in candidate order, each proved to name the file beside it.
 *
 * Throws rather than returning a partial list: every caller of this is about to
 * write these strings into immutable contract storage.
 */
export async function seedableCids(directory: string = METADATA_DIR): Promise<string[]> {
  const problems = await manifestProblems(directory);
  if (problems.length > 0) {
    throw new Error(`the candidate metadata is not seedable:\n  ${problems.join("\n  ")}`);
  }

  return (await readManifest(directory)).candidates.map((entry) => entry.cid);
}

/** One document's bytes, without needing a manifest to exist yet. */
export interface DocumentContents {
  file: string;
  bytes: Uint8Array;
  metadata: CandidateMetadata;
}

/**
 * Every document on disk, in seed order.
 *
 * Deliberately independent of the manifest: this is what `pin-metadata.ts` runs
 * on, and on a first run the manifest does not exist yet.
 */
export async function documentContents(
  directory: string = METADATA_DIR,
): Promise<DocumentContents[]> {
  return Promise.all(
    (await documentFiles(directory)).map(async (file) => {
      const bytes = new Uint8Array(await readFile(path.join(directory, file)));
      const parsed: unknown = JSON.parse(new TextDecoder().decode(bytes));
      const problem = metadataProblem(parsed);

      if (problem !== null) {
        throw new Error(`${file}: ${problem}`);
      }

      return { file, bytes, metadata: parsed as CandidateMetadata };
    }),
  );
}

/** The documents themselves, with the CIDs the manifest records for them. */
export async function candidateDocuments(
  directory: string = METADATA_DIR,
): Promise<CandidateDocument[]> {
  const manifest = await readManifest(directory);

  return Promise.all(
    manifest.candidates.map(async (entry) => {
      const bytes = new Uint8Array(await readFile(path.join(directory, entry.file)));

      return {
        ...entry,
        bytes,
        metadata: JSON.parse(new TextDecoder().decode(bytes)) as CandidateMetadata,
      };
    }),
  );
}

/** The manifest's entries when it exists, or `[]` when it does not. */
export async function existingManifest(directory: string = METADATA_DIR): Promise<ManifestEntry[]> {
  try {
    return (await readManifest(directory)).candidates;
  } catch {
    return [];
  }
}

/**
 * Writes the manifest in a fixed form: two-space indent, LF, one trailing
 * newline, keys in a fixed order. `git diff --exit-code` is part of this
 * repository's CI, so a regenerated manifest has to be byte-identical to the
 * committed one to be a no-op.
 */
export async function writeManifest(
  entries: readonly ManifestEntry[],
  directory: string = METADATA_DIR,
): Promise<void> {
  const body = entries
    .map(
      (entry) =>
        `    {\n      "file": ${JSON.stringify(entry.file)},\n      "cid": ${JSON.stringify(entry.cid)}\n    }`,
    )
    .join(",\n");

  await writeFile(
    path.join(directory, MANIFEST_NAME),
    `{\n  "candidates": [\n${body}\n  ]\n}\n`,
    "utf8",
  );
}
